export const listData = [
  {
    id: 1,
    model: "Fortuner",
    price: 500000,
    img: "https://content.toyota.com.ph/uploads/prices/579/002_579_1695008067438_000.webp",
    address: "PB",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 21000,
    transmission: "AT",
    latitude: 14.5995,
    longitude: 120.9842,
  },
  {
    id: 2,
    model: "Innova",
    price: 400000,
    img: "https://w7.pngwing.com/pngs/845/662/png-transparent-white-toyota-innova-crysta-suv-toyota-rav4-car-minivan-toyota-innova-crysta-thailand-sedan-vehicle-transport-thumbnail.png",
    address: "SP",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 41000,
    transmission: "MT",
    latitude: 15.5995,
    longitude: 120.9842,
  },
  {
    id: 3,
    model: "Vios",
    price: 200000,
    img: "https://w7.pngwing.com/pngs/433/370/png-transparent-toyota-vios-2018-kia-optima-toyota-vitz-toyota-compact-car-sedan-car.png",
    address: "NG",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 500000,
    transmission: "AT",
    latitude: 13.5995,
    longitude: 121.9842,
  },
  {
    id: 4,
    model: "Wigo",
    price: 200000,
    img: "https://toyotaalbay.com.ph/wp-content/uploads/2023/08/wigo-orange-met.png",
    address: "G",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 11000,
    transmission: "AT",
    latitude: 12.5995,
    longitude: 120.9842,
  },
  {
    id: 5,
    model: "Fortuner",
    price: 500000,
    img: "https://content.toyota.com.ph/uploads/prices/579/002_579_1695008067438_000.webp",
    address: "PB",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 21000,
    transmission: "AT",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 6,
    model: "Innova",
    price: 400000,
    img: "https://w7.pngwing.com/pngs/845/662/png-transparent-white-toyota-innova-crysta-suv-toyota-rav4-car-minivan-toyota-innova-crysta-thailand-sedan-vehicle-transport-thumbnail.png",
    address: "SP",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 41000,
    transmission: "MT",
    latitude: 53.4808,
    longitude: -2.2426,
  },
  {
    id: 7,
    model: "Vios",
    price: 200000,
    img: "https://w7.pngwing.com/pngs/433/370/png-transparent-toyota-vios-2018-kia-optima-toyota-vitz-toyota-compact-car-sedan-car.png",
    address: "NG",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 500000,
    transmission: "AT",
    latitude: 53.8008,
    longitude: -1.5491,
  },
  {
    id: 8,
    model: "Wigo",
    price: 200000,
    img: "https://toyotaalbay.com.ph/wp-content/uploads/2023/08/wigo-orange-met.png",
    address: "G",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 11000,
    transmission: "AT",
    latitude: 53.8008,
    longitude: -1.5491,
  },
];

export const singlePostData = {
  id: 1,
  model: "Fortuner GRS",
  make: "Toyota",
  year: 2023,
  price: 500000,
  images: [
    "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/original/2022-toyota-fortuner-exterior-quarter-front-philippines-62fefdab14b9b.webp",
    "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/original/2022-toyota-fortuner-wiper-controls-62feff13c4157.webp",
    "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/original/2022-toyota-fortuner-exterior-quarter-front-62feff13c8afe.webp",
    "https://d1hv7ee95zft1i.cloudfront.net/custom/car-model-photo/original/2022-toyota-fortuner-exterior-quarter-rear-62feff13c01f7.webp",
  ],
  address: "PB",
  city: "Sta. Maria",
  mileage: 21000,
  transmission: "AT",
  color: "White",
  fuel: "Diesel",
  latitude: 14.5995,
  longitude: 120.9842,

  description:
    "Inside, the Fortuner can seat seven people, with the option to fold the third-row seats to the side in order to accommodate more cargo. The Fortuner also has the advantage of having better amenities compared to the cars it shares its platform with.",
};

export const userData = {
  id: 1,
  name: "John Doe",
  img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
};
