export const listData = [
  {
    id: 1,
    model: "Fortuner",
    price: 500000,
    img: "https://content.toyota.com.ph/uploads/prices/579/002_579_1695008067438_000.webp",
    address: "PB",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 21000,
    transmission: "AT",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 2,
    model: "Innova",
    price: 400000,
    img: "https://w7.pngwing.com/pngs/845/662/png-transparent-white-toyota-innova-crysta-suv-toyota-rav4-car-minivan-toyota-innova-crysta-thailand-sedan-vehicle-transport-thumbnail.png",
    address: "SP",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 41000,
    transmission: "MT",
    latitude: 53.4808,
    longitude: -2.2426,
  },
  {
    id: 3,
    model: "Vios",
    price: 200000,
    img: "https://w7.pngwing.com/pngs/433/370/png-transparent-toyota-vios-2018-kia-optima-toyota-vitz-toyota-compact-car-sedan-car.png",
    address: "NG",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 500000,
    transmission: "AT",
    latitude: 53.8008,
    longitude: -1.5491,
  },
  {
    id: 4,
    model: "Wigo",
    price: 200000,
    img: "https://toyotaalbay.com.ph/wp-content/uploads/2023/08/wigo-orange-met.png",
    address: "G",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 11000,
    transmission: "AT",
    latitude: 53.8008,
    longitude: -1.5491,
  },
  {
    id: 5,
    model: "Fortuner",
    price: 500000,
    img: "https://content.toyota.com.ph/uploads/prices/579/002_579_1695008067438_000.webp",
    address: "PB",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 21000,
    transmission: "AT",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 6,
    model: "Innova",
    price: 400000,
    img: "https://w7.pngwing.com/pngs/845/662/png-transparent-white-toyota-innova-crysta-suv-toyota-rav4-car-minivan-toyota-innova-crysta-thailand-sedan-vehicle-transport-thumbnail.png",
    address: "SP",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 41000,
    transmission: "MT",
    latitude: 53.4808,
    longitude: -2.2426,
  },
  {
    id: 7,
    model: "Vios",
    price: 200000,
    img: "https://w7.pngwing.com/pngs/433/370/png-transparent-toyota-vios-2018-kia-optima-toyota-vitz-toyota-compact-car-sedan-car.png",
    address: "NG",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 500000,
    transmission: "AT",
    latitude: 53.8008,
    longitude: -1.5491,
  },
  {
    id: 8,
    model: "Wigo",
    price: 200000,
    img: "https://toyotaalbay.com.ph/wp-content/uploads/2023/08/wigo-orange-met.png",
    address: "G",
    city: "Sta. Maria",
    make: "Toyota",
    mileage: 11000,
    transmission: "AT",
    latitude: 53.8008,
    longitude: -1.5491,
  },
];

export const singlePostData = {
  id: 1,
  title: "Beautiful Apartment",
  price: 1200,
  images: [
    "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  ],
  bedRooms: 2,
  bathroom: 1,
  size: 861,
  latitude: 51.5074,
  longitude: -0.1278,
  city: "London",
  address: "1234 Broadway St",
  school: "250m away",
  bus: "100m away",
  restaurant: "50m away",
  description:
    "Future alike hill pull picture swim magic chain seed engineer nest outer raise bound easy poetry gain loud weigh me recognize farmer bare danger. actually put square leg vessels earth engine matter key cup indeed body film century shut place environment were stage vertical roof bottom lady function breeze darkness beside tin view local breathe carbon swam declared magnet escape has from pile apart route coffee storm someone hold space use ahead sheep jungle closely natural attached part top grain your grade trade corn salmon trouble new bend most teacher range anybody every seat fifteen eventually",
};

export const userData = {
  id: 1,
  name: "John Doe",
  img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
};
